backend:
  name: git-gateway
  repo: nvmc-sor-rogaland/website
  branch: master
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/33f9a476-5339-4a7c-93f1-747917f55add/pkce
  auth_token_endpoint: /sites/33f9a476-5339-4a7c-93f1-747917f55add/token
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "assets/uploads"

collections:
  - name: "posts"
    label: "Innlegg"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "post" }
      - { name: "title", label: "Tittel", widget: "string" }
      - { name: "subtitle", label: "Subtitle", widget: "string", required: false }
      - { name: "cover-img", label: "Omslagsbilde", widget: "image", required: false }
      - { name: "body", label: "Innhold", widget: "richtext" }

  - name: "schedules"
    label: "Terminlister"
    label_singular: "Terminliste"
    folder: "_schedules/"
    create: true
    slug: "{{fields.year}}"
    fields:
      - {
          name: "year",
          label: "År",
          widget: "number",
          value_type: "int",
          pattern: ["^[0-9]{4}$", "Må inneholde et årstall"],
        }
      - { name: "layout", label: "Layout", widget: "hidden", default: "schedules" }
      - { name: "title", label: "Tittel", widget: "string" }
      - { name: "subtitle", label: "Ingress", widget: "string" }

  - name: "events"
    label: "Arrangementer"
    label_singular: "Arrangement"
    folder: "_events/"
    create: true
    path: "{{ start | date('YYYY') }}/{{ start | date('DD-MM-YYYY') }}-{{ slug }}"
    media_folder: "{{media_folder}}"
    fields:
      - { name: "layout", label: "Layout", widget: "hidden", default: "event" }
      - { name: "title", label: "Tittel", widget: "string" }
      - { name: "subtitle", label: "Ingress", widget: "string", required: false }
      - { name: "cover-img", label: "Omslagsbilde", widget: "image", required: false }
      - { name: "start", label: "Startdato og -tidspunkt", widget: "datetime", format: "YYYY-MM-DD HH:mm" }
      - { name: "end", label: "Sluttdato og -tidspunkt", widget: "datetime", format: "YYYY-MM-DD HH:mm", required: false }
      - { name: "location", label: "Sted", widget: "string" }
      - { name: "body", label: "Beskrivelse", widget: "richtext" }


  - name: "pages"
    label: "Sider"
    label_singular: "Side"
    files:
      - name: "join"
        label: "Bli medlem"
        file: "blimedlem.md"
        fields:
          - { name: "layout", label: "Layout", widget: "hidden", default: "page" }
          - { name: "title", label: "Tittel", widget: "string" }
          - { name: "subtitle", label: "Ingress", widget: "string", required: false }
          - { name: "body", label: "Innhold", widget: "richtext" }
      - name: "about"
        label: "Om oss"
        file: "omoss.md"
        fields:
          - { name: "layout", label: "Layout", widget: "hidden", default: "page" }
          - { name: "title", label: "Tittel", widget: "string" }
          - { name: "subtitle", label: "Ingress", widget: "string", required: false }
          - { name: "body", label: "Innhold", widget: "richtext" }

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

logo:
  src: https://raw.githubusercontent.com/nvmc-sor-rogaland/website/refs/heads/master/assets/img/logo.png
  show_in_header: true

site_url: https://nvmc-sor-rogaland.github.io/website

locale: "nb_no"
